import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		// Node.js builtins - mark as external so they're not bundled
		// On mobile, these will fail to load but our code handles that gracefully
		...builtins,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	// Changed from 'node' to 'neutral' for cross-platform compatibility
	// 'neutral' doesn't assume any runtime environment
	platform: 'neutral',
	// Provide shims/definitions for Node.js globals that might be referenced
	define: {
		'global': 'globalThis',
		// Prevent any inline crypto references from being treated as Node.js crypto
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
	},
	// Ensure we don't inject any Node.js polyfills
	inject: [],
	// Main fields resolution order - prefer browser/module entries
	mainFields: ['browser', 'module', 'main'],
	// Conditions for package.json exports field
	conditions: ['browser', 'import', 'default'],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
