import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, existsSync } from "fs";
import { resolve } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Manually load .env file if it exists (no external dependency needed)
function loadEnvFile() {
	const envPath = resolve(process.cwd(), '.env');
	if (existsSync(envPath)) {
		console.log('📁 Loading environment variables from .env file');
		const envContent = readFileSync(envPath, 'utf-8');
		for (const line of envContent.split('\n')) {
			const trimmed = line.trim();
			// Skip comments and empty lines
			if (!trimmed || trimmed.startsWith('#')) continue;
			
			const [key, ...valueParts] = trimmed.split('=');
			if (key && valueParts.length > 0) {
				let value = valueParts.join('='); // Handle values with = in them
				// Remove surrounding quotes if present
				if ((value.startsWith('"') && value.endsWith('"')) || 
				    (value.startsWith("'") && value.endsWith("'"))) {
					value = value.slice(1, -1);
				}
				process.env[key.trim()] = value;
			}
		}
	} else {
		console.log('ℹ️  No .env file found at', envPath);
	}
}

// Load .env file
loadEnvFile();

// Get OAuth credentials from environment variables
const CATCHMENT_CLIENT_ID = process.env.CATCHMENT_CLIENT_ID || "";
const CATCHMENT_CLIENT_SECRET = process.env.CATCHMENT_CLIENT_SECRET || "";

if (!CATCHMENT_CLIENT_ID || !CATCHMENT_CLIENT_SECRET) {
	console.warn("\n⚠️  Warning: OAuth credentials not found in environment variables.");
	console.warn("   Set CATCHMENT_CLIENT_ID and CATCHMENT_CLIENT_SECRET before building.\n");
	console.warn("   Option 1: Create a .env file with:");
	console.warn("      CATCHMENT_CLIENT_ID=your-client-id");
	console.warn("      CATCHMENT_CLIENT_SECRET=your-client-secret\n");
	console.warn("   Option 2: Export them in your shell:");
	console.warn("      export CATCHMENT_CLIENT_ID=your-client-id");
	console.warn("      export CATCHMENT_CLIENT_SECRET=your-client-secret\n");
} else {
	console.log('✅ OAuth credentials loaded successfully');
	console.log(`   Client ID: ${CATCHMENT_CLIENT_ID.substring(0, 20)}...`);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	// This is the key part - define compile-time constants
	define: {
		"process.env.CATCHMENT_CLIENT_ID": JSON.stringify(CATCHMENT_CLIENT_ID),
		"process.env.CATCHMENT_CLIENT_SECRET": JSON.stringify(CATCHMENT_CLIENT_SECRET),
	},
	// Ensure we're building for browser environment (important for mobile)
	platform: "browser",
	// Don't bundle node builtins - let Obsidian handle them on desktop
	mainFields: ["browser", "module", "main"],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}